"use client";

import { useState } from "react";

import type { UnavailabilityFieldErrors, UnavailabilityFormValues } from "@/features/unavailabilities/types/unavailability";

export function UnavailabilityPeriodFields({ values, errors, disabled, timezone }: { values: Pick<UnavailabilityFormValues, "startsAt" | "endsAt" | "allDay">; errors: UnavailabilityFieldErrors; disabled: boolean; timezone: string }) {
  const [allDay, setAllDay] = useState(values.allDay);
  const control = "h-11 w-full rounded-lg border border-input bg-card px-3 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/20 disabled:bg-muted";
  return <fieldset className="grid gap-5 rounded-xl border border-border p-4 sm:grid-cols-2"><legend className="px-1 font-semibold">Período</legend><label className="flex items-center gap-3 sm:col-span-2"><input name="allDay" type="checkbox" checked={allDay} disabled={disabled} onChange={(event) => setAllDay(event.target.checked)} /><span className="text-sm font-medium">Dia inteiro</span></label><div className="space-y-1.5"><label htmlFor="startsAt" className="block text-sm font-medium">{allDay ? "Data inicial" : "Início"}</label><input key={`start-${allDay}`} id="startsAt" name="startsAt" type={allDay ? "date" : "datetime-local"} required disabled={disabled} defaultValue={values.startsAt} aria-invalid={errors.startsAt?.[0] ? true : undefined} aria-describedby={errors.startsAt?.[0] ? "startsAt-error" : undefined} className={control} />{errors.startsAt?.[0] ? <p id="startsAt-error" role="alert" className="text-sm text-destructive">{errors.startsAt[0]}</p> : null}</div><div className="space-y-1.5"><label htmlFor="endsAt" className="block text-sm font-medium">{allDay ? "Data final (inclusiva)" : "Final"}</label><input key={`end-${allDay}`} id="endsAt" name="endsAt" type={allDay ? "date" : "datetime-local"} required disabled={disabled} defaultValue={values.endsAt} aria-invalid={errors.endsAt?.[0] ? true : undefined} aria-describedby={errors.endsAt?.[0] ? "endsAt-error" : undefined} className={control} />{errors.endsAt?.[0] ? <p id="endsAt-error" role="alert" className="text-sm text-destructive">{errors.endsAt[0]}</p> : null}</div><p className="text-xs leading-5 text-muted-foreground sm:col-span-2">Horários interpretados em {timezone}. O período segue [início, fim): o instante final não fica bloqueado.</p></fieldset>;
}
