import Link from "next/link";
import { TechnicianStatusAction } from "@/features/technicians/components/technician-status-action";
import type { TechnicianDetails as Details } from "@/features/technicians/types/technician";

function formatCpf(value: string | null) { return value ? value.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/, "$1.$2.$3-$4") : "—"; }
function formatPhone(value: string | null) { return value ? value.replace(/^(\d{2})(\d{4,5})(\d{4})$/, "($1) $2-$3") : "—"; }

export function TechnicianDetails({ organizationSlug, technician, timezone }: { organizationSlug: string; technician: Details; timezone: string }) {
  const updatedAt = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: timezone }).format(new Date(technician.updated_at));
  return <div className="space-y-6">
    <section className="rounded-xl border border-zinc-200 bg-white p-5"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><h2 className="text-xl font-semibold">{technician.name}</h2><p className="mt-1 text-sm text-zinc-600">{technician.job_title ?? "Cargo não informado"}</p></div><span className={`self-start rounded-full px-3 py-1 text-xs font-semibold ${technician.active ? "bg-emerald-100 text-emerald-800" : "bg-zinc-200 text-zinc-700"}`}>{technician.active ? "Ativo" : "Inativo"}</span></div>
      <dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3">{[["CPF",formatCpf(technician.document)],["E-mail",technician.email ?? "—"],["Telefone",formatPhone(technician.phone)],["Base",`${technician.base_city}/${technician.base_state}`],["Usuário de acesso",technician.profile_id ? "Vinculado" : "Não vinculado"],["Atualizado em",updatedAt]].map(([title, value]) => <div key={title}><dt className="text-zinc-500">{title}</dt><dd className="mt-1 font-medium text-zinc-900">{value}</dd></div>)}</dl>
    </section>
    <section className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="font-semibold">Especialidades</h2>{technician.skills.length ? <ul className="mt-4 grid gap-3 sm:grid-cols-2">{technician.skills.map((skill) => <li key={skill.skillId} className="rounded-lg bg-zinc-50 p-3"><div className="flex justify-between gap-2"><span className="font-medium">{skill.skillName}</span>{skill.isPrimary ? <span className="text-xs font-semibold text-amber-700">Principal</span> : null}</div><p className="mt-1 text-sm text-zinc-600">Nível {skill.proficiencyLevel}{skill.skillActive ? "" : " · Especialidade inativa"}</p></li>)}</ul> : <p className="mt-2 text-sm text-zinc-500">Nenhuma especialidade associada.</p>}</section>
    <section className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="font-semibold">Condução de veículo</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-zinc-500">Pode dirigir</dt><dd className="mt-1 font-medium">{technician.can_drive_company_vehicle ? "Sim" : "Não"}</dd></div><div><dt className="text-zinc-500">CNH / categoria</dt><dd className="mt-1 font-medium">{technician.driver_license_number ? `${technician.driver_license_number} · ${technician.driver_license_category}` : "—"}</dd></div><div><dt className="text-zinc-500">Validade</dt><dd className="mt-1 font-medium">{technician.driver_license_expires_at ? new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${technician.driver_license_expires_at}T00:00:00Z`)) : "—"}</dd></div></dl></section>
    {technician.notes ? <section className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="font-semibold">Observações</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-zinc-700">{technician.notes}</p></section> : null}
    <div className="flex flex-wrap items-start gap-4"><Link href={`/app/${organizationSlug}/cadastros/tecnicos/${technician.id}/editar`} className="inline-flex h-10 items-center rounded-lg bg-zinc-950 px-4 text-sm font-semibold text-white">Editar técnico</Link><TechnicianStatusAction organizationSlug={organizationSlug} technicianId={technician.id} active={technician.active} /></div>
  </div>;
}
