import Link from "next/link";
import { TechnicianStatusAction } from "@/features/technicians/components/technician-status-action";
import type { TechnicianListItem } from "@/features/technicians/types/technician";

function date(value: string, timezone: string) { try { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: timezone }).format(new Date(value)); } catch { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value)); } }
function driving(technician: TechnicianListItem) { if (!technician.can_drive_company_vehicle) return "Não"; const today = new Date().toISOString().slice(0, 10); return technician.driver_license_expires_at && technician.driver_license_expires_at >= today ? "Sim" : "CNH vencida"; }
function Badge({ active }: { active: boolean }) { return <span className={active ? "rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-800" : "rounded-full bg-zinc-200 px-2.5 py-1 text-xs font-semibold text-zinc-700"}>{active ? "Ativo" : "Inativo"}</span>; }
function SkillBadges({ technician }: { technician: TechnicianListItem }) { return <div className="flex max-w-xs flex-wrap gap-1">{technician.skills.length ? technician.skills.map((skill) => <span key={skill.skillId} className="rounded bg-zinc-100 px-2 py-1 text-xs text-zinc-700">{skill.skillName}{skill.isPrimary ? " ★" : ""}</span>) : <span className="text-sm text-zinc-500">—</span>}</div>; }

export function TechnicianList({ organizationSlug, technicians, timezone, hasFilters }: { organizationSlug: string; technicians: TechnicianListItem[]; timezone: string; hasFilters: boolean }) {
  const base = `/app/${organizationSlug}/cadastros/tecnicos`;
  if (technicians.length === 0) return <div className="rounded-xl border border-dashed border-zinc-300 bg-white p-10 text-center"><h2 className="font-semibold">{hasFilters ? "Nenhum técnico encontrado" : "Nenhum técnico cadastrado"}</h2><p className="mt-2 text-sm text-zinc-600">{hasFilters ? "Altere ou limpe os filtros." : "Cadastre o primeiro técnico da organização."}</p>{!hasFilters ? <Link href={`${base}/novo`} className="mt-4 inline-flex h-10 items-center rounded-lg bg-zinc-950 px-4 text-sm font-semibold text-white">Novo técnico</Link> : null}</div>;
  return <><div className="hidden overflow-x-auto rounded-xl border border-zinc-200 md:block"><table className="w-full min-w-[1050px] text-left"><thead className="bg-zinc-50 text-xs uppercase text-zinc-600"><tr>{["Técnico","Cidade-base","Especialidades","Pode dirigir","Status","Atualizado em","Ações"].map((title) => <th key={title} className="px-4 py-3">{title}</th>)}</tr></thead><tbody className="divide-y bg-white">{technicians.map((technician) => <tr key={technician.id}>
    <td className="px-4 py-4 align-top"><p className="font-semibold text-zinc-950">{technician.name}</p><p className="text-sm text-zinc-500">{technician.job_title ?? "Sem cargo informado"}</p></td>
    <td className="px-4 py-4 align-top text-sm text-zinc-700">{technician.base_city}/{technician.base_state}</td>
    <td className="px-4 py-4 align-top"><SkillBadges technician={technician} /></td>
    <td className="px-4 py-4 align-top text-sm text-zinc-700">{driving(technician)}</td>
    <td className="px-4 py-4 align-top"><Badge active={technician.active} /></td>
    <td className="whitespace-nowrap px-4 py-4 text-sm text-zinc-600">{date(technician.updated_at, timezone)}</td><td className="px-4 py-4"><div className="flex gap-3"><Link href={`${base}/${technician.id}`} className="text-sm font-medium">Abrir</Link><Link href={`${base}/${technician.id}/editar`} className="text-sm font-medium">Editar</Link><TechnicianStatusAction organizationSlug={organizationSlug} technicianId={technician.id} active={technician.active} /></div></td></tr>)}</tbody></table></div>
    <div className="space-y-3 md:hidden">{technicians.map((technician) => <article key={technician.id} className="space-y-3 rounded-xl border border-zinc-200 bg-white p-4"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{technician.name}</h2><p className="text-sm text-zinc-500">{technician.job_title ?? `${technician.base_city}/${technician.base_state}`}</p></div><Badge active={technician.active} /></div><div className="flex flex-wrap gap-1">{technician.skills.map((skill) => <span key={skill.skillId} className="rounded bg-zinc-100 px-2 py-1 text-xs">{skill.skillName}</span>)}</div><p className="text-sm">Pode dirigir: {driving(technician)}</p><div className="flex gap-3 border-t pt-3"><Link href={`${base}/${technician.id}`} className="text-sm font-medium">Abrir</Link><Link href={`${base}/${technician.id}/editar`} className="text-sm font-medium">Editar</Link><TechnicianStatusAction organizationSlug={organizationSlug} technicianId={technician.id} active={technician.active} /></div></article>)}</div></>;
}
