import Link from "next/link";

import { VehicleActiveStateAction } from "@/features/vehicles/components/vehicle-active-state-action";
import { VehicleStatusAction } from "@/features/vehicles/components/vehicle-status-action";
import type { VehicleListItem, VehicleOperationalStatus } from "@/features/vehicles/types/vehicle";

function formatPlate(value: string) { return value.replace(/^([A-Z]{3})([0-9]{4})$/, "$1-$2"); }
function formatMileage(value: number | null) { return value === null ? "Não informada" : `${new Intl.NumberFormat("pt-BR").format(value)} km`; }
function formatUpdatedAt(value: string, timezone: string) { try { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: timezone }).format(new Date(value)); } catch { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value)); } }
function operationalLabel(status: VehicleOperationalStatus) { return { available: "Disponível", maintenance: "Em manutenção", blocked: "Bloqueado" }[status]; }
function OperationalBadge({ status }: { status: VehicleOperationalStatus }) { const colors = { available: "bg-emerald-100 text-emerald-800", maintenance: "bg-amber-100 text-amber-800", blocked: "bg-red-100 text-red-800" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${colors[status]}`}>{operationalLabel(status)}</span>; }
function ActiveBadge({ active }: { active: boolean }) { return <span className={active ? "rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-800" : "rounded-full bg-zinc-200 px-2.5 py-1 text-xs font-semibold text-zinc-700"}>{active ? "Ativo" : "Inativo"}</span>; }
function dateWarning(value: string | null, label: string, expiredLabel: string) { if (!value) return null; const today = new Date(); today.setHours(0, 0, 0, 0); const target = new Date(`${value}T00:00:00`); const days = Math.ceil((target.getTime() - today.getTime()) / 86400000); if (days < 0) return expiredLabel; if (days <= 30) return `${label} vence em ${days} dias`; return null; }

export function VehicleList({ organizationSlug, vehicles, timezone, hasFilters }: { organizationSlug: string; vehicles: VehicleListItem[]; timezone: string; hasFilters: boolean }) {
  const base = `/app/${organizationSlug}/cadastros/veiculos`;
  if (vehicles.length === 0) return <div className="rounded-xl border border-dashed border-zinc-300 bg-white p-10 text-center"><h2 className="font-semibold">{hasFilters ? "Nenhum veículo encontrado" : "Nenhum veículo cadastrado"}</h2><p className="mt-2 text-sm text-zinc-600">{hasFilters ? "Altere ou limpe os filtros." : "Cadastre o primeiro veículo da organização."}</p>{!hasFilters ? <Link href={`${base}/novo`} className="mt-4 inline-flex h-10 items-center rounded-lg bg-zinc-950 px-4 text-sm font-semibold text-white">Novo veículo</Link> : null}</div>;
  return <><div className="hidden overflow-x-auto rounded-xl border border-zinc-200 lg:block"><table className="w-full min-w-[1250px] text-left"><thead className="bg-zinc-50 text-xs uppercase text-zinc-600"><tr>{["Veículo","Placa","Capacidade","Cidade-base","Quilometragem","Condição","Status","Atualizado em","Ações"].map((title) => <th key={title} className="px-4 py-3">{title}</th>)}</tr></thead><tbody className="divide-y bg-white">{vehicles.map((vehicle) => { const warning = dateWarning(vehicle.licensing_expires_at, "Licenciamento", "Licenciamento vencido") ?? dateWarning(vehicle.maintenance_due_at, "Manutenção", "Manutenção vencida"); return <tr key={vehicle.id}><td className="px-4 py-4 align-top"><p className="font-semibold">{vehicle.brand} {vehicle.model}</p><p className="text-xs text-zinc-500">{vehicle.manufacture_year ?? "—"}/{vehicle.model_year ?? "—"}</p>{warning ? <p className="mt-1 text-xs font-medium text-amber-700">{warning}</p> : null}</td><td className="px-4 py-4 font-mono text-sm">{formatPlate(vehicle.plate)}</td><td className="px-4 py-4 text-sm">{vehicle.passenger_capacity}</td><td className="px-4 py-4 text-sm">{vehicle.base_city}/{vehicle.base_state}</td><td className="px-4 py-4 text-sm">{formatMileage(vehicle.current_mileage)}</td><td className="px-4 py-4"><OperationalBadge status={vehicle.operational_status} /></td><td className="px-4 py-4"><ActiveBadge active={vehicle.active} /></td><td className="whitespace-nowrap px-4 py-4 text-sm text-zinc-600">{formatUpdatedAt(vehicle.updated_at, timezone)}</td><td className="space-y-2 px-4 py-4"><div className="flex gap-3"><Link href={`${base}/${vehicle.id}`} className="text-sm font-medium">Abrir</Link><Link href={`${base}/${vehicle.id}/editar`} className="text-sm font-medium">Editar</Link><VehicleActiveStateAction organizationSlug={organizationSlug} vehicleId={vehicle.id} active={vehicle.active} /></div><VehicleStatusAction organizationSlug={organizationSlug} vehicleId={vehicle.id} currentStatus={vehicle.operational_status} /></td></tr>; })}</tbody></table></div>
    <div className="space-y-3 lg:hidden">{vehicles.map((vehicle) => <article key={vehicle.id} className="space-y-3 rounded-xl border border-zinc-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{vehicle.brand} {vehicle.model}</h2><p className="font-mono text-sm text-zinc-600">{formatPlate(vehicle.plate)}</p></div><ActiveBadge active={vehicle.active} /></div><div className="flex flex-wrap gap-2"><OperationalBadge status={vehicle.operational_status} /><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-xs">{vehicle.passenger_capacity} pessoas</span></div><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-zinc-500">Base</dt><dd>{vehicle.base_city}/{vehicle.base_state}</dd></div><div><dt className="text-xs text-zinc-500">Quilometragem</dt><dd>{formatMileage(vehicle.current_mileage)}</dd></div></dl><div className="flex flex-wrap gap-3 border-t pt-3"><Link href={`${base}/${vehicle.id}`} className="text-sm font-medium">Abrir</Link><Link href={`${base}/${vehicle.id}/editar`} className="text-sm font-medium">Editar</Link><VehicleActiveStateAction organizationSlug={organizationSlug} vehicleId={vehicle.id} active={vehicle.active} /></div><VehicleStatusAction organizationSlug={organizationSlug} vehicleId={vehicle.id} currentStatus={vehicle.operational_status} /></article>)}</div></>;
}
