import Link from "next/link";
import { CalendarClock, FileCheck2, Gauge, MapPin, Users, Wrench } from "lucide-react";

import { SectionHeader } from "@/components/page/section-header";
import { Badge } from "@/components/ui/badge";
import { buttonStyles } from "@/components/ui/button";
import { InlineAlert } from "@/components/ui/inline-alert";
import { TripStatusBadge } from "@/features/trips/components/trip-badges";
import { formatDateOnly, getVehicleDateState, vehicleOperationalLabel } from "@/features/vehicles/application/vehicle-presentation";
import { VehicleDateBadge, VehicleOperationalBadge } from "@/features/vehicles/components/vehicle-badges";
import { VehicleStatusAction } from "@/features/vehicles/components/vehicle-status-action";
import type { Vehicle, VehicleOperationalPeriods } from "@/features/vehicles/types/vehicle";

function Field({ label, value, className = "", mono = false }: { label: string; value: string; className?: string; mono?: boolean }) { return <div className={className}><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className={`mt-1 text-sm text-foreground ${mono ? "font-mono" : ""}`}>{value}</dd></div>; }
function formatMileage(value: number | null) { return value === null ? "Não informada" : `${new Intl.NumberFormat("pt-BR").format(value)} km`; }
function formatPeriod(startsAt: string, endsAt: string, timezone: string, allDay = false) { const date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: timezone }); const dateTime = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: timezone }); if (allDay) return `${date.format(new Date(startsAt))} a ${date.format(new Date(new Date(endsAt).getTime() - 1))} · dia inteiro`; return `${dateTime.format(new Date(startsAt))} a ${dateTime.format(new Date(endsAt))}`; }

export function VehicleDetails({ organizationSlug, vehicle, timezone, referenceDate, referenceTime, periods }: { organizationSlug: string; vehicle: Vehicle; timezone: string; referenceDate: string; referenceTime: string; periods: VehicleOperationalPeriods }) {
  const referenceTimestamp = new Date(referenceTime).getTime();
  const licensingState = getVehicleDateState(vehicle.licensing_expires_at, referenceDate);
  const maintenanceState = getVehicleDateState(vehicle.maintenance_due_at, referenceDate);
  const currentUnavailability = periods.unavailabilities.find((item) => new Date(item.startsAt).getTime() <= referenceTimestamp);
  const nextUnavailability = currentUnavailability ?? periods.unavailabilities[0];
  const currentReservation = periods.reservations.find((item) => new Date(item.startsAt).getTime() <= referenceTimestamp);
  const nextOperationalPeriod = [
    ...(nextUnavailability && !currentUnavailability ? [{ kind: "unavailability" as const, startsAt: nextUnavailability.startsAt }] : []),
    ...(periods.reservations[0] && !currentReservation ? [{ kind: "reservation" as const, startsAt: periods.reservations[0].startsAt }] : []),
  ].sort((left, right) => left.startsAt.localeCompare(right.startsAt))[0];
  const availability = currentUnavailability ? `Indisponível até ${new Intl.DateTimeFormat("pt-BR", { timeZone: timezone }).format(new Date(currentUnavailability.endsAt))}` : currentReservation ? "Em viagem reservada" : nextOperationalPeriod ? `${nextOperationalPeriod.kind === "unavailability" ? "Próxima indisponibilidade" : "Reserva futura"} em ${new Intl.DateTimeFormat("pt-BR", { timeZone: timezone }).format(new Date(nextOperationalPeriod.startsAt))}` : "Sem bloqueio cadastrado";
  const updatedAt = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: timezone }).format(new Date(vehicle.updated_at));
  const unavailabilityPath = `/app/${organizationSlug}/planejamento/indisponibilidades?resource=vehicles&resourceId=${vehicle.id}`;
  return <div className="space-y-6">{!vehicle.active ? <InlineAlert tone="warning">Este veículo está inativo e permanece disponível apenas para consulta e histórico.</InlineAlert> : null}<section aria-label="Resumo operacional" className="grid overflow-hidden rounded-2xl border border-border bg-card sm:grid-cols-2 xl:grid-cols-6">{[
    { icon: Users, label: "Capacidade", value: `${vehicle.passenger_capacity} pessoas` },
    { icon: Gauge, label: "Quilometragem", value: formatMileage(vehicle.current_mileage) },
    { icon: MapPin, label: "Base", value: `${vehicle.base_city}/${vehicle.base_state}` },
    { icon: Wrench, label: "Condição", value: vehicleOperationalLabel(vehicle.operational_status) },
    { icon: CalendarClock, label: "Disponibilidade", value: availability },
    { icon: FileCheck2, label: "Licenciamento", value: licensingState === "expired" ? "Vencido" : licensingState === "not_informed" ? "Não informado" : `Até ${formatDateOnly(vehicle.licensing_expires_at)}` },
  ].map(({ icon: Icon, label, value }, index) => <div key={label} className={`flex gap-3 p-4 sm:p-5 ${index < 5 ? "border-b border-border xl:border-b-0 xl:border-r" : ""}`}><Icon aria-hidden="true" className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div></div>)}</section>

    <nav aria-label="Seções do veículo" className="flex gap-1 overflow-x-auto rounded-xl border border-border bg-card p-1"><a href="#visao-geral" className={buttonStyles({ variant: "ghost", size: "sm" })}>Visão geral</a><a href="#documentacao" className={buttonStyles({ variant: "ghost", size: "sm" })}>Documentação</a><a href="#indisponibilidades" className={buttonStyles({ variant: "ghost", size: "sm" })}>Indisponibilidades</a><a href="#reservas" className={buttonStyles({ variant: "ghost", size: "sm" })}>Reservas</a></nav>

    <section id="visao-geral" aria-labelledby="vehicle-overview-title" className="scroll-mt-6 rounded-2xl border border-border bg-card p-5 sm:p-6"><SectionHeader id="vehicle-overview-title" title="Visão geral" description="Identificação, capacidade e dados operacionais do veículo." /><dl className="mt-6 grid gap-x-8 gap-y-5 sm:grid-cols-2 lg:grid-cols-3"><Field label="Placa" value={vehicle.plate} mono /><Field label="Marca" value={vehicle.brand} /><Field label="Modelo" value={vehicle.model} /><Field label="Ano de fabricação" value={vehicle.manufacture_year?.toString() ?? "Não informado"} /><Field label="Ano do modelo" value={vehicle.model_year?.toString() ?? "Não informado"} /><Field label="Capacidade total" value={`${vehicle.passenger_capacity} pessoas, incluindo motorista`} /><Field label="Quilometragem" value={formatMileage(vehicle.current_mileage)} /><Field label="Localidade-base" value={`${vehicle.base_city}/${vehicle.base_state}`} /><Field label="Situação cadastral" value={vehicle.active ? "Ativo" : "Inativo"} /><Field label="Condição operacional" value={vehicleOperationalLabel(vehicle.operational_status)} /><Field label="Atualizado em" value={updatedAt} /><Field label="Observações" value={vehicle.notes ?? "Nenhuma observação registrada."} className="whitespace-pre-wrap sm:col-span-2 lg:col-span-3" /></dl><div className="mt-6 rounded-xl border border-border bg-muted/50 p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Condição operacional</p><div className="mt-2"><VehicleOperationalBadge status={vehicle.operational_status} /></div><p className="mt-2 max-w-2xl text-xs leading-5 text-muted-foreground">A situação cadastral define se o veículo pode ser utilizado no sistema. A condição operacional informa se ele está apto para viagens.</p></div><VehicleStatusAction organizationSlug={organizationSlug} vehicleId={vehicle.id} currentStatus={vehicle.operational_status} vehicleLabel={vehicle.plate} /></div></div></section>

    <section id="documentacao" aria-labelledby="vehicle-documentation-title" className="scroll-mt-6 rounded-2xl border border-border bg-card p-5 sm:p-6"><SectionHeader id="vehicle-documentation-title" title="Documentação e manutenção" description="Datas cadastrais usadas no acompanhamento operacional da frota." /><div className="mt-6 grid gap-5 md:grid-cols-2"><div className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Licenciamento</h3><VehicleDateBadge state={licensingState} subject="Licenciamento" /></div><dl className="mt-4"><Field label="Validade" value={formatDateOnly(vehicle.licensing_expires_at)} /></dl></div><div className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Manutenção prevista</h3><VehicleDateBadge state={maintenanceState} subject="Manutenção" /></div><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Data prevista" value={formatDateOnly(vehicle.maintenance_due_at)} /><Field label="Quilometragem atual" value={formatMileage(vehicle.current_mileage)} /></dl></div></div><p className="mt-4 text-xs leading-5 text-muted-foreground">Os alertas de proximidade são apenas apresentação visual dos próximos 30 dias e não substituem as validações operacionais do servidor.</p></section>

    <section id="indisponibilidades" aria-labelledby="vehicle-unavailability-title" className="scroll-mt-6 rounded-2xl border border-border bg-card p-5 sm:p-6"><SectionHeader id="vehicle-unavailability-title" title="Indisponibilidades" description="Períodos em que o veículo não pode ser reservado." actions={vehicle.active ? <Link href={`/app/${organizationSlug}/planejamento/indisponibilidades/veiculos/nova?vehicleId=${vehicle.id}`} className={buttonStyles({ variant: "secondary", size: "sm" })}>Registrar indisponibilidade</Link> : undefined} />{periods.unavailabilities.length ? <ul className="mt-5 divide-y divide-border rounded-xl border border-border">{periods.unavailabilities.slice(0, 5).map((item) => { const current = new Date(item.startsAt).getTime() <= referenceTimestamp; return <li key={item.id} className="grid gap-2 p-4 sm:grid-cols-[minmax(10rem,0.7fr)_minmax(14rem,1fr)_minmax(10rem,1fr)]"><div><p className="font-medium">{item.typeName}</p><Badge tone={current ? "warning" : "info"} className="mt-2">{current ? "Em andamento" : "Futura"}</Badge></div><p className="text-sm">{formatPeriod(item.startsAt, item.endsAt, timezone, item.allDay)}</p><p className="text-sm text-muted-foreground">{item.reason ?? "Motivo não informado"}</p></li>; })}</ul> : <p className="mt-5 rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">Nenhuma indisponibilidade atual ou futura.</p>}<div className="mt-4"><Link href={unavailabilityPath} className="text-sm font-semibold text-primary hover:underline">Visualizar todas as indisponibilidades</Link></div></section>

    <section id="reservas" aria-labelledby="vehicle-reservations-title" className="scroll-mt-6 rounded-2xl border border-border bg-card p-5 sm:p-6"><SectionHeader id="vehicle-reservations-title" title="Reservas futuras" description="Viagens que atualmente bloqueiam a agenda deste veículo." />{periods.reservations.length ? <ul className="mt-5 divide-y divide-border rounded-xl border border-border">{periods.reservations.slice(0, 5).map((reservation) => <li key={reservation.tripId} className="grid gap-3 p-4 md:grid-cols-[minmax(8rem,0.5fr)_minmax(14rem,1fr)_minmax(15rem,1fr)_auto] md:items-center"><div><Link href={`/app/${organizationSlug}/planejamento/viagens/${reservation.tripId}`} className="font-mono text-sm font-semibold text-primary hover:underline">{reservation.code}</Link><div className="mt-2"><TripStatusBadge status={reservation.status} /></div></div><div><p className="text-sm font-medium">{reservation.title}</p><p className="mt-1 text-xs text-muted-foreground">{reservation.clientName}</p></div><p className="text-sm">{formatPeriod(reservation.startsAt, reservation.endsAt, timezone)}</p><Link href={`/app/${organizationSlug}/planejamento/viagens/${reservation.tripId}`} className={buttonStyles({ variant: "ghost", size: "sm" })}>Visualizar viagem</Link></li>)}</ul> : <p className="mt-5 rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">Nenhuma reserva futura vinculada.</p>}</section>
  </div>;
}
